repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
    exclude: mkdocs.yml
  - id: debug-statements
  - id: end-of-file-fixer
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.251
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
    exclude: mkdocs.yml
