site_name: Homepage of Patrik Hlobil

# Repository
repo_name: Blog
repo_url: https://github.com/PatrikHlobil/Blog

nav:
- Home: index.md
- Links: links.md
- '... | blogs/*'

plugins:
- search:
    lang: en
- awesome-pages

theme:
  name: material
  logo: static/portrait.jpg
  favicon: static/favicon-32x32.png
  features:
  - search.highlight
  - search.suggest
  - search.share
  - toc.follow
  - toc.integrate
  - navigation.instant

markdown_extensions:
- toc:
    permalink: true
- attr_list
- admonition
- md_in_html
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !%21python/name:pymdownx.superfences.fence_code_format
