site_name: Blog of Patrik Hlobil

# Repository
repo_name: Blog
repo_url: https://github.com/PatrikHlobil/Blog

nav:
- Home: index.md
- Links: links.md

plugins:
- search:
    lang: en

theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/31643597?v=4
  favicon: static/favicon-32x32.png
  features:
  - search.highlight
  - search.suggest
  - search.share
  - toc.follow
  - toc.integrate
  - navigation.instant

markdown_extensions:
- toc:
    permalink: true
