site_name: Homepage of Patrik Hlobil

# Repository
repo_name: Blog
repo_url: https://github.com/PatrikHlobil/Blog

nav:
- Home: index.md
- Links: links.md
- '... | blogs/*'

plugins:
- search:
    lang: en
- awesome-pages

theme:
  name: material
  logo: static/portrait.jpg
  favicon: static/favicon-32x32.png
  features:
  - search.highlight
  - search.suggest
  - search.share
  - toc.follow
  - toc.integrate
  - navigation.instant
  - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
- toc:
    permalink: true
- attr_list
- admonition
- md_in_html
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

extra_css: [static/custom.css]
