parameters:
  python: '3.11'
name: pre-commit

jobs:
- job: pre-commit
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.python }}
  - script: sudo apt update
    displayName: install pre-commit
  - script: sudo apt install pre-commit
    displayName: install pre-commit
  - script: pre-commit install
    displayName: install pre-commit
  - script: pre-commit run --all-files --show-diff-on-failure
    displayName: run pre-commit
