name: Publish to Github Pages

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/configure-pages@v6
    - uses: actions/checkout@v7
    - name: Install uv
      uses: astral-sh/setup-uv@v9
      with:
        version: 0.12.3
        python-version: 3.14
        enable-cache: true
    - name: Build site
      run: |
        uv sync --locked --no-dev
        uv run --no-dev zensical build --clean
    - uses: actions/upload-pages-artifact@v5
      with:
        path: site
    - uses: actions/deploy-pages@v5
      id: deployment
