name: Publish to Github Pages

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python Version
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install poetry
      run: |
        curl -fsS https://install.python-poetry.org | python - -y
    - name: Generate Static HTML
      run: |
        rm -rf docs
        poetry install
        generate-html --content-dir content --target-dir docs/sites
        mkdocs build -d docs
    - name: Update Github Pages
      run: |
        git config --global user.email "patrik.hlobil@gmail.com"
        git config --global user.name "Patrik Hlobil"
        git fetch
        git checkout gh-pages
        git add docs/
        git commit -m "Update Github Pages for '${GITHUB_SHA}'"
        git push
